### ISSUE TITLE
"Device cannot be reached" after updating to 2025.3.0b0

### ISSUE THREAD

**Issue by maxbengtzen** [Tasshack/dreame-vacuum#866]
**Describe the bug**

After updating HA to 2025.3.0b0 beta release I can not longer reach my Dreame device. I'm running the latest beta release of the Dreame Vacuum HACS integration (v2.0.0b16).

**To Reproduce**

Update to 2025.3.0b0 release.

**Expected behavior**
Reaching the device.

**Screenshots**

![Image](https://github.com/user-attachments/assets/5c5fc842-bdb4-4fa9-ba0d-9c22b2877c84)

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: D10s
 - Firmware Version [e.g. 1156]: 4.1.8_1415
 - Home Assistant Version: 2025.3.0b0
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable):

**Comment by maxbengtzen** [comment]
> Any logs?

```
Felet härrör från en anpassad integration.

Loggare: custom_components.dreame_vacuum
Källa: custom_components/dreame_vacuum/coordinator.py:443
integration: Dreame Vacuum (dokumentation, ärenden)
Inträffade först: 11:16:21 (127 tillfällen)
Senast loggade: 14:02:50

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2815, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached
```

**Comment by ridderr** [comment]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.dreame_vacuum
Bron: custom_components/dreame_vacuum/coordinator.py:443
integratie: Dreame Vacuum (documentatie, problemen)
Eerst voorgekomen: 26 februari 2025 om 22:22:39 (1525 gebeurtenissen)
Laatst gelogd: 15:34:38

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2673, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached
Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2670, in update self.connect_device() ~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1936, in connect_device self._request_properties() ~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 666, in _request_properties result = self._protocol.get_properties(props[:15]) File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1232, in get_properties return self.send("get_properties", parameters=parameters, retry_count=retry_count) ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1224, in send raise DeviceException("Unable to discover the device over cloud") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

**Comment by Cheerpipe** [comment]
I was just about to report the same bug. Integration ([v2.0.0b16](https://github.com/Tasshack/dreame-vacuum/releases/tag/v2.0.0b16)) not working with 2025.3 beta. It does work if I revert to the previous version, 2025.2.

`Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 437, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2815, in update raise DeviceUpdateFailedException("Device cannot be reached") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceUpdateFailedException: Device cannot be reached`

**Comment by Cheerpipe** [comment]
https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html

Breaking changes on paho 2.0.0

**Comment by Cheerpipe** [comment]
In the mean time, this can be used as a dirty workarround.

In protocol.py 

add 
`from paho.mqtt import client as mqtt_client`
under
`from paho.mqtt.client import Client`

<img width="417" alt="Image" src="https://github.com/user-attachments/assets/03dfe5ed-10a6-40c0-af9d-fc5cad20685b" />

and add
`mqtt_client.CallbackAPIVersion.VERSION1,`
under
`self._client = Client(`

<img width="1139" alt="Image" src="https://github.com/user-attachments/assets/02fbd9f7-8515-45a9-8617-97cb4d685edf" />

**Comment by ChristophCaina** [comment]
> This may be related to `paho.mqtt` is being `v2.0` on the latest core.

That's probably it.
It was bumped to 2.1.0 with 2025.3.0

**Comment by JiHeR91** [comment]
@Cheerpipe many thanks, works perfectly here ^^

**Comment by ccMatrix** [comment]
Any chance for a new v2.0.0 beta build with the fix?

**Comment by myevit** [comment]
same.

**Comment by s2kta4** [comment]
need to restart home assistant after this change to take affect?

**Comment by jeffreygarc** [comment]
> need to restart home assistant after this change to take affect?

Yes

**Comment by BinGor2010** [comment]
+1 here. 
We have the Same Problem. 

@Tasshack 
Thanks for the lot of work.

**Comment by maxservice** [comment]
works fine thank you.

**Comment by rbaptista1995** [comment]
work perfect to me thank you!!!

**Comment by AlexZT2000** [comment]
Yes, it worked. Thanks! How soon is the release of the non-beta version with vacuum cleaners planned?

**Comment by Matess67** [comment]
> In the meantime, this can be used as a dirty workarround.
> 
> In protocol.py
> 
> add `from paho.mqtt import client as mqtt_client` under `from paho.mqtt.client import Client`
> <img alt="Image" width="417" src="https://private-user-images.githubusercontent.com/972765/417722544-03dfe5ed-10a6-40c0-af9d-fc5cad20685b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEyODUyOTcsIm5iZiI6MTc0MTI4NDk5NywicGF0aCI6Ii85NzI3NjUvNDE3NzIyNTQ0LTAzZGZlNWVkLTEwYTYtNDBjMC1hZjlkLWZjNWNhZDIwNjg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwNlQxODE2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjA4YzNiYWViYjE4MDJjYzAwOGNhYWI1NjQyYWRkODcwZmJhYzM0NTkxMGZmNTkwNjJkYTAzMjEzMmNlYmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t-qwadwYMoAOIDCzgXJN9NtPIISP7JeZnXDmz1T4ux4">
> 
> and add `mqtt_client.CallbackAPIVersion.VERSION1,` under `self._client = Client(`
> <img alt="Image" width="1139" src="https://private-user-images.githubusercontent.com/972765/417722360-02fbd9f7-8515-45a9-8617-97cb4d685edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEyODUyOTcsIm5iZiI6MTc0MTI4NDk5NywicGF0aCI6Ii85NzI3NjUvNDE3NzIyMzYwLTAyZmJkOWY3LTg1MTUtNDVhOS04NjE3LTk3Y2I0ZDY4NWVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwNlQxODE2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWRjMDRlYmI1YTgxMzdhNTBkMGUzYTFkNTA5ZDAyMDM0ZjcyMWY3MjI3NWFmNjAzMTU5ZWIzM2VmMGI4ZGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8Z5OyJxLpUu0wy0s5ykV0hf-bTWXMyhOq_Ovaf4eFl0">

Many thanks, it works fine

**Comment by Johnnyd2036** [comment]
i MADE THIS CHANGES IN /homeassistant/custom_components/dreame_vacuum/dreame/protocol.py
still not working..!

**Comment by ChristophCaina** [comment]
> In the meantime, this can be used as a dirty workarround.
> 
> In protocol.py
> 
> add `from paho.mqtt import client as mqtt_client` under `from paho.mqtt.client import Client`
> 
> <img alt="Image" width="417" src="https://private-user-images.githubusercontent.com/972765/417722544-03dfe5ed-10a6-40c0-af9d-fc5cad20685b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNDA1NDYsIm5iZiI6MTc0MTM0MDI0NiwicGF0aCI6Ii85NzI3NjUvNDE3NzIyNTQ0LTAzZGZlNWVkLTEwYTYtNDBjMC1hZjlkLWZjNWNhZDIwNjg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwOTM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODg3NzVkOWRmNzY4MjQzOGM2ZDQ4MzFhMmJlYzY3NzJlYmJkNWUwN2I4ODAxMTZjZTFjZjExOTQzNGY1YzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gcp_W4usK0iGQPa4mi-cpxACG-_SkK6QtMm4YR6OQMQ">
> and add `mqtt_client.CallbackAPIVersion.VERSION1,` under `self._client = Client(`
> 
> <img alt="Image" width="1139" src="https://private-user-images.githubusercontent.com/972765/417722360-02fbd9f7-8515-45a9-8617-97cb4d685edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzNDA1NDYsIm5iZiI6MTc0MTM0MDI0NiwicGF0aCI6Ii85NzI3NjUvNDE3NzIyMzYwLTAyZmJkOWY3LTg1MTUtNDVhOS04NjE3LTk3Y2I0ZDY4NWVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwOTM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWUzZTdhYzIyMjE0OGM5ZTY3ZjEzNWY2MDYyODU0ZDI3NWJkNGYxY2JhMDRmNzU4NGE0YzZmOTdmMWEwNDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5plV2WEGQoMY5FQtaIzRO9Bx3PJvjogG6xcHJmTIjxw">

somehow, this seems not to work for me.
Not sure, but maybe, because I am already running v2.0.0b16 ?

**Comment by maxservice** [comment]
double check syntax save and reboot

**Comment by ChristophCaina** [comment]
- [x] double checked (it was copy&paste) 
```
from paho.mqtt.client import Client
# paho-mqtt fix
from paho.mqtt import client as mqtt_client
```

```
                        try:
                            host = self._host.split(":")
                            self._client = Client(
                               # paho_mqtt fix
                                mqtt_client.CallbackAPIVersion.VERSION1,
                                f"{self._strings[53]}{self._uid}{self._strings[54]}{DreameVacuumMiHomeCloudProtocol.get_random_agent_id()}{self._strings[54]}{host[0]}",
                                clean_session=True,
                                userdata=self,
                            )
```
- [x] rebooted already several times due to other things and changes

---
turns out, that in addition to the paho-mqtt issue, there was another issue with the integration not being able to login into my account.

**Comment by Maetzi87** [comment]
Thank you very much for the fast solution!! ❤️❤️

**Comment by vanheerde** [comment]
> I have already made the changes related to paho 2.0 on my local. I am going to release a new version next week.

Hi! :) When do you think you will rollout the update? Thank you!

**Comment by Maetzi87** [comment]
Its already out, v2.0.0b17. ;-)

**Comment by Atraxmaster** [comment]
With HA version 2025.3.1 the message still appears even for Dreame Vacuum HACS (v2.0.0b17). Any other solutions?

**Comment by Cheerpipe** [comment]
It must be an issue with Dreame's cloud. I've had intermittent problems initializing the integration (US Region) due to timeout issues. In my case, I fixed it by increasing the number of retries and raising the timeout from a reasonable 3 to a crazy 20.

Try changing Protocol.py Chage  timeout=3, to somthing like  timeout=10,

**Comment by BlaM** [comment]
I also get the feeling that this is a Dreame "backend" problem. I'm still on HA 2025.2.5 + Dreame Vacuum HACS v2.0.0b16 and run into the same problems (EU Region). 

That makes compatibility issues with HA 2025.3 unlikely.

**Comment by Maetzi87** [comment]
My integration is up and running since last update, so maybe it depends on the vacuum?

![Image](https://github.com/user-attachments/assets/9664161c-ee78-4c79-aaf3-d11dce475022)
![Image](https://github.com/user-attachments/assets/2c7ca67c-6e7a-4616-a5ec-30ca7f3718ac)
![Image](https://github.com/user-attachments/assets/3143456c-cae6-4899-a18f-24e45ff55730)

**Comment by BlaM** [comment]
X40 for me. 

![Image](https://github.com/user-attachments/assets/9ff75a75-175f-4f39-b66e-6094e8ccb878)

It just stopped to work 5 days ago. Was ok before that.

**Comment by arndt123** [comment]
I feel a bit ashamed that I need to ask. But how do I upgrade to v2.0.0b17 without loosing or messing up everything I have right now with v2.0.0b16? For all other integrations or add-on I have in HA an update is shown in settings, once available. Seems to be different here and I want to avoid deleting everything and starting from scratch.  So any advice is appreciated. At least the once that help me. THX.

**Comment by Maetzi87** [comment]
Normally, HA should  prompt the update in the update-section.

If it does not, try the following:
Go to HACs, find the Integration. In the upper right corner click the 3 dots.
There should be something like "download again" (sorry, my interface is german, so it says "erneut herunterladen".)  In the pop-up, you can read, which version you are about to download, change this with the field below if necessary (should be set to newest version automatically anyway).

Don't worry, "download again" does not delete anything, it just updates the config of the integration, so your settings should stay. However I always recommend making a backup before any updates.

**Comment by arndt123** [comment]
Big thanks. It is so easy, if you know where to find it. Works with 2025.2.5, let's see what it will do with 2025.3.1. Or if it requires the changes in protocol.py mentioned earlier in this thread. But again, big thanks for the super fast response.

**Comment by petrum6** [comment]
Bonjour, Quand j'installe la version V2.0.0b17 cela fait rebooter mon HA en continu suis je le seul dans ce cas?

**Comment by bennyrbg** [comment]
I am running 2 robots (D10s Pro and D9) on the integration

Got the problem mention here on update to 2025.3.1 with the D10s Pro (D9 still running)
Fixed it with v2.0.0b17
Now updated to 2025.3.2
D10s Pro still running, D9 has the problem now

Hope that helps and thanks for your work!

**Comment by Guacam-Ole** [comment]
I can approve that 2.0.0b17 fixed the issue for me (L10s Pro Ultra Heat)

**Comment by StayPirate** [comment]
I upgraded the integration to `v2.0.0b17` and HA to `v2025.3.3`, but that **did not solve** the problem for my Dreame L10s Ultra:

```
This error originated from a custom integration.

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:467
integration: Dreame Vacuum (documentation, issues)
First occurred: 11:04:55 (1 occurrences)
Last logged: 11:04:55

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 461, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2913, in update self.connect_device() ~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 2116, in connect_device self._request_properties() ~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 726, in _request_properties result = self._protocol.get_properties(props[:15]) File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1285, in get_properties return self.send("get_properties", parameters=parameters, retry_count=retry_count) ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1277, in send raise DeviceException("Unable to discover the device over cloud") from None custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud
```

**Comment by PlayFaster** [comment]
> I upgraded the integration to `v2.0.0b17` and HA to `v2025.3.3`, but that **did not solve** the problem for my Dreame L10s Ultra:



Hi. The process that I followed, based on advice in one of the other threads was to re-download v2.0.0b17 via HACS and then restart Home Assistant. This worked for me, might be worth a try.

**Comment by StayPirate** [comment]
Confirm, it works! Thank you :)

**Comment by mstrop** [comment]
The problem with 2.0.0b17, 2025.3.3 amd Xiaomi X20+

![Image](https://github.com/user-attachments/assets/e9b8a5d9-4bc9-4a1c-a9ab-6d91d68fa003)

**Comment by BlaM** [comment]
> X40 for me.
> 
> It just suddenly stopped to work 5 days ago. Was ok before that.

... and just like it stopped to work two weeks ago it suddenly started to work again yesterday - and I didn't even have time to work on HomeAssistant or even reboot the system in the last 10 days...

**Comment by abuttez** [comment]
> > The problem with 2.0.0b17, 2025.3.3 amd Xiaomi X20+
> > ![Image](https://github.com/user-attachments/assets/e9b8a5d9-4bc9-4a1c-a9ab-6d91d68fa003)
> 
> This issue only affects Dreame Cloud users so your problem is not same.

I do have the exact same error with 2.0.0b17, 2025.3.4 and Xiaomi X20 (Xiaomi account login)

**Comment by Liionboy** [comment]
Again same problem:

![Image](https://github.com/user-attachments/assets/09028b32-68f4-4831-8a43-2f6677d8a092)

![Image](https://github.com/user-attachments/assets/8b005d16-c3e7-4ec4-8449-c1448b6298b8)

**Comment by BlaM** [comment]
For me it's randomly on/off over the last few months. Mostly not working, sometimes working - which gives me the feeling that it is actually a server-side problem with Dreame, because it keeps changing even when there are no updates to this component.

**Comment by Liionboy** [comment]
Telnet is work on eu.iot.dreame.tech port 13267, but i can't login on this page https://smarthome.dreame.tech/

**Comment by jove01** [comment]
> For me it's randomly on/off over the last few months. Mostly not working, sometimes working - which gives me the feeling that it is actually a server-side problem with Dreame, because it keeps changing even when there are no updates to this component.

The same Problem here

**Comment by anthonyma94** [comment]
Having this issue, restarted HA and now it won't connect. Running v2.0.0b17 with a Dreame L40 Ultra, HA 2025.5.3.

**Comment by Liionboy** [comment]
At me problem was at Pi-Hole, he block acces to some link who comunicate with cloud of dream vacum

**Comment by DrumSlayers** [comment]
my home assistant directly use Google Public DNS 8.8.8.8 and Cloudflare 1.1.1.1, so no issues from this so far
And it can register & fetch the robot name from dreame servers

**Comment by Liionboy** [comment]
I did something like this:

![Image](https://github.com/user-attachments/assets/ccf9b9f0-97d7-452b-ace9-2d95b5d9e3b8)

With disable is not working

**Comment by DrumSlayers** [comment]
> my home assistant directly use Google Public DNS 8.8.8.8 and Cloudflare 1.1.1.1, so no issues from this so far And it can register & fetch the robot name from dreame servers

Any clue about the original issue @Tasshack ? 
As said, i'm not using any adblocker or fake DNS resolver, and domains does respond.
Authentication & robot name fetching works, but it stops next

```
boiteauxframboises:/config# nslookup eu.iot.dreame.tech
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   eu.iot.dreame.tech
Address: 8.209.124.241

boiteauxframboises:/config# nslookup dreame-eu.oss-eu-central-1.aliyuncs.com
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   dreame-eu.oss-eu-central-1.aliyuncs.com
Address: 47.254.187.24

boiteauxframboises:/config#
```

**Comment by georgenecro** [comment]
![Image](https://github.com/user-attachments/assets/22bb8947-91d5-4eb4-b299-b544bc7154aa)

I have the same problem, when i updated to latest HA version it can't connect to cloud. No adblocks/pihole etc.

**Comment by georgenecro** [comment]
![Image](https://github.com/user-attachments/assets/6a70f150-f433-4db8-b026-64f26e29db7d)

There is no EU option.

**Comment by georgenecro** [comment]
Beta v2.0.0b19 worked well. Connected via Xiaomi Home Account (server DE).
